### ISSUE TITLE
[doc] Create clear USB vs WiFi Nugget software documentation

### ISSUE THREAD

**Issue by robbpaulsen** [HakCat-Tech/USB-Nugget#72]
Hi, first of all  big fan and just got my hands on my rubber nugget really like its design. On the issues topic

-  I'm having a lot of mixed does, donts and what actually applies to my esp32-s2 rubber nugget and the wifi nugget.
-  The second topic is on the to up to date flashing process and again is the mixed between the docs and your channel's content. Obviously because when I cant understand something from the documentation I look up for the channels content to see if Im messing something up or didnt actually understood.

Have a nice day, hope to get back from you soon..

**Comment by brandonpaiz** [comment]
Hi @robbpaulsen,

Thanks for being a fan :)

> I'm having a lot of mixed does, donts and what actually applies to my esp32-s2 rubber nugget and the wifi nugget.

Understandable, we're working to increase clarity on the differences between the two. In the meantime, do you have any specific questions I can help you with? As for flashing, you can use [these directions](https://usbnugget.com/docs/guides/update-with-chrome/) after grabbing the .bin from the [release page](https://github.com/HakCat-Tech/USB-Nugget/releases/).

Let us know how it goes!

**Comment by robbpaulsen** [comment]
Thanks for the replay, so I managed to what I think is the usb nugget, the device already appears on my file manager as 'CIRCUITPY' , but when I trie to copy the nuggetDeauth, nuggetinvader and nuggetPacketMonitor I cant seem to get it to run, none of them, then I tried to to copy the 5 payload repo but still same result, so Im stuck there now

**Comment by robbpaulsen** [comment]
Oh I forgot, also i cant get the display to show other of the nugget "faces"

**Comment by brandonpaiz** [comment]
I believe those projects are only compatible with the Wi-Fi Nugget (which I know less about), not the USB-Nugget
@AlexLynd, can ya weigh in here?

**Comment by AlexLynd** [comment]
Hey! Sorry I didn't see the issue earlier, but I apologize for the brand confusion around the WiFi & USB Nugget - this is one of the biggest problems we're currently fixing & documenting, since its one of the most frequent issues we get!

Our current product split is between 2 boards - the **WiFi Nugget** (for running WiFi attack & network defense tools) and the **USB Nugget** (for running USB attack payloads).  These 2 devices have completely different WiFi chips on board and have hardware limitations.  

In terms of supported software, the **WiFi Nugget** (ESP8266 based) can run the Deauther (a WiFi attack suite), the Invader (a network defense toolkit), and the PacketMonitor (a WiFi recon tool), but **can't** run any of our USB attack software.  Similarly, the **USB Nugget** (ESP32-S2 based) only runs USB / HID attacks, and can't run any WiFi attacks or WiFi monitoring tools. 

It looks like you purchased a USB Nugget, which is probably why those other programs aren't working on your Nugget :(
I hope this clarifies things a little bit!  Fortunately, we are working on adding some more cross platform functionality for the WiFi tools in the future - so stay posted for when we drop those :)

- Alex

**Comment by robbpaulsen** [comment]
Thanks a lot for getting back to me. Ok now it makes sense why all the trouble, ok but its still a good board, Ill just focus on the actual docs of the Usb nugget and and pick a project down the road and see what develops. Thanks, and have a good day.
